# Generated by Django 4.0.6 on 2022-08-02 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiares',
            name='fecha_nacimiento',
        ),
        migrations.AddField(
            model_name='familiares',
            name='Profesion',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
